# Configuration for Alacritty, the GPU enhanced terminal emulator.

env:
  TERM: xterm-256color

# Font configuration
font:
  normal:
    family: Iosevka
    style: Regular
  bold:
    style: Semibold
  italic:
    style: Italic
  bold_italic:
    style: Bold Italic

  # Point size
  size: 10.0

  # Offset is the extra space around each character. `offset.y` can be thought
  # of as modifying the line spacing, and `offset.x` as modifying the letter
  # spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the
  # right, increasing `y` moves the glyph upward.
  glyph_offset:
    x: 0
    y: 0

  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`.
  use_thin_strokes: false

# If `true`, bold text is drawn using the bright color variants.
#draw_bold_text_with_bright_colors: false

# Colors (Nord)
# Source: https://github.com/arcticicestudio/nord-alacritty/blob/develop/src/nord.yml
colors:
  primary:
    background: '#2e3440'      # nord0; darkest in Polar Night
    foreground: '#d8dee9'      # nord4; darkest in Snow Storm
    dim_foreground: '#a5abb6'  # intermediate gray
  cursor:
    text: '#2e3440'    # nord0; darkest in Polar Night
    cursor: '#d8dee9'  # nord4; darkest in Snow Storm
  vi_mode_cursor:
    text: '#2e3440'    # nord0; darkest in Polar Night
    cursor: '#d8dee9'  # nord0; darkest in Polar Night
  selection:
    text: CellForeground
    background: '#4c566a'   # nord3; lightest in Polar Night
  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'
    bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'    # nord1; one shade lighter than nord0
    red: '#bf616a'      # nord11
    green: '#a3be8c'    # nord14
    yellow: '#ebcb8b'   # nord13
    cyan: '#88c0d0'     # nord8; 2nd-lightest in Frost
    blue: '#81a1c1'     # nord9; 2nd-darkest in Frost
    magenta: '#b48ead'  # nord15
    white: '#e5e9f0'    # nord5; intermediate in Snow Storm
  bright:
    black: '#4c566a'    # nord3; lightest in Polar Night
    red: '#bf616a'      # nord11
    green: '#a3be8c'    # nord14
    yellow: '#ebcb8b'   # nord13
    cyan: '#8fbcbb'     # nord7; lightest in Frost
    blue: '#81a1c1'     # nord9; 2nd-darkest in Frost
    magenta: '#b48ead'  # nord15
    white: '#eceff4'    # nord6; lightest in Snow Storm
  dim:
    black: '#373e4d'    # dark black-blue-gray
    red: '#94545d'      # muted version of nord11
    green: '#809575'    # muted version of nord14
    yellow: '#b29e75'   # muted version of nord13
    blue: '#68809a'     # muted version of nord10
    magenta: '#8c738c'  # muted version of nord15
    cyan: '#6d96a5'     # muted version of nord7
    white: '#aeb3bb'    # darkened version of nord4

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Block

    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: Off

  # Vi mode cursor style
  #
  # If the vi mode cursor style is `None` or not specified, it will fall back to
  # the style of the active value of the normal cursor.
  #
  # See `cursor.style` for available options.
  vi_mode_style: Beam

  # Cursor blinking interval in milliseconds.
  blink_interval: 750

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

  # Thickness of the cursor relative to the cell width as floating point number
  # from `0.0` to `1.0`.
  thickness: 0.15


key_bindings:
  # Key bindings to control font size from keyboard 
  - { key: Minus,   mods: Control,   action: DecreaseFontSize }
  - { key: Plus,    mods: Control,   action: IncreaseFontSize }
  - { key: Key0,    mods: Control,   action: ResetFontSize    }
# # Use for Alt to work as Mod key on macOS
# # See https://github.com/alacritty/alacritty/issues/62
#   - { key: Key1,    mods: Alt,       chars: "\x1b1"           }
#   - { key: Key2,    mods: Alt,       chars: "\x1b2"           }
#   - { key: Key3,    mods: Alt,       chars: "\x1b3"           }
#   - { key: Key4,    mods: Alt,       chars: "\x1b4"           }
#   - { key: Key5,    mods: Alt,       chars: "\x1b5"           }
#   - { key: Key6,    mods: Alt,       chars: "\x1b6"           }
#   - { key: Key7,    mods: Alt,       chars: "\x1b7"           }
#   - { key: Key8,    mods: Alt,       chars: "\x1b8"           }
#   - { key: Key9,    mods: Alt,       chars: "\x1b9"           }
