#!/usr/bin/env bash
# NAME
#     keys - Displays active key interception layer, if any
# 
# DESCRIPTION
#     Just a home-rolled script to prominently display any current active key
#     interception layers (e.g. for Inkscape) in i3 status bar.
#     Relies on the existences of temporary files (hard-coded names; must be
#     coordinated with other parts of the interception layer elsewhere on the
#     file system) to indicate if an interception layer is active.
# CAVEATS
#     Assumes only one interception layer is active at a given time.

# Totally hacky but does the job well for my use case:
# Space-delimited list of indictor_file,status key,value pairs (this technique
# only works, of course, if file names don't contain spaces or commas).
INDICATOR_FILES="/tmp/inkscape_keys,INKSCAPE /tmp/foo,FOO"
STATUS="Default"
FG_DEFAULT="#ffffff"
FG_ACTIVE="#000000"
BG_ACTIVE="#e6c88a"  # yellow

# If an indicator file is present, set the file's associated status
for indicator_pair in ${INDICATOR_FILES}; do
  file="${indicator_pair%,*}"
  status="${indicator_pair##*,}"
  if [[ -e ${file} ]]; then
    STATUS=${status}
    break
  fi
done

# White space for padding
echo " ${LABEL} ${STATUS} "  # long text
echo " ${LABEL} ${STATUS} "  # short text

# Foreground and background color
if [[ ${STATUS} != "Default" ]]; then
  echo ${FG_ACTIVE}
  echo ${BG_ACTIVE}
else
  echo ${FG_DEFAULT}
fi
